service: backend-without-domain

frameworkVersion: '>=3.15.0'

useDotenv: true
provider:
  name: aws
  profile: serverless-profile
  runtime: nodejs14.x
  stage: ${opt:stage, 'production'}
  region: us-west-2
  timeout: 30
  memorySize: 128
  iam:
    role: ${env:LAMBDA_ROLE_ARN}
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    STAGE: ${opt:stage, 'production'}

custom:
  stage: ${opt:stage, 'production'}

functions:
  backend:
    handler: src/backend.default
